ALTER TABLE CLIENTE
ADD CONSTRAINT CHK_SEXO CHECK (sexo IN ('Masculino', 'Femenino', 'Otro'));

ALTER TABLE CLIENTE
ADD CONSTRAINT UK_EMAIL UNIQUE (email);

ALTER TABLE CLIENTE
ADD CONSTRAINT CHK_FECHA_NACIMIENTO CHECK (fecha_nacimiento < GETDATE());

ALTER TABLE TIPO_HABITACION
ADD CONSTRAINT CHK_CAPACIDAD_POSITIVA CHECK (capacidad > 0);

ALTER TABLE HABITACION
ADD CONSTRAINT UK_NUMERO_HABITACION UNIQUE (numero_habitacion);

ALTER TABLE HABITACION
ADD CONSTRAINT CHK_ESTADO_OCUPACION CHECK (estado_ocupacion IN (0, 1));

ALTER TABLE DETALLE_RESERVA
ADD CONSTRAINT CHK_FECHA_ENTRADA_PASADA CHECK (fecha_entrada <= CURRENT_TIMESTAMP);
